# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\",\n\x0cScheduleData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\";\n\x0fScheduleDetails\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1a\n\x06movies\x18\x02 \x03(\x0b\x32\n.MovieData\"H\n\tMovieData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t2\xbf\x01\n\x08Schedule\x12+\n\x11GetScheduleByDate\x12\x05.Date\x1a\r.ScheduleData\"\x00\x12\x35\n\x18GetScheduleDetailsByDate\x12\x05.Date\x1a\x10.ScheduleDetails\"\x00\x12-\n\x0b\x41\x64\x64Schedule\x12\r.ScheduleData\x1a\r.ScheduleData\"\x00\x12 \n\x0e\x44\x65leteSchedule\x12\x05.Date\x1a\x05.Date\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULEDATA']._serialized_start=18
  _globals['_SCHEDULEDATA']._serialized_end=62
  _globals['_DATE']._serialized_start=64
  _globals['_DATE']._serialized_end=84
  _globals['_SCHEDULEDETAILS']._serialized_start=86
  _globals['_SCHEDULEDETAILS']._serialized_end=145
  _globals['_MOVIEDATA']._serialized_start=147
  _globals['_MOVIEDATA']._serialized_end=219
  _globals['_SCHEDULE']._serialized_start=222
  _globals['_SCHEDULE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
